name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown,aarch64-apple-ios,x86_64-apple-ios,aarch64-apple-ios-sim,armv7-linux-androideabi,aarch64-linux-android
      
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry

      - name: Cache cargo target
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target

      - name: Install OpenSSL
        if: runner.os == 'macOS'
        run: brew install openssl@3

      - name: Export OpenSSL path for dx
        if: runner.os == 'macOS'
        run: echo "DYLD_FALLBACK_LIBRARY_PATH=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
  

      - name: Install Dioxus CLI
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall dioxus-cli
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        
      - name: Install platform-specific dependencies
        shell: bash
        run: |
          case "$RUNNER_OS" in
            "macOS")
              brew install create-dmg
              ;;
            "Windows")
              choco install wixtoolset -y
              ;;
          esac

      - name: Bundle desktop apps
        shell: bash
        run: |
          case "$RUNNER_OS" in
            "macOS")
              dx bundle --platform desktop --release --package-types "macos" --package-types "dmg"
              ;;
            "Windows")
              dx bundle --platform desktop --release --package-types "nsis" --package-types "msi"
              ;;
          esac

      - name: Bundle iOS app
        if: runner.os == 'macOS'
        run: dx bundle --platform ios --release --package-types "ios"

      - name: Build Android app
        run: dx build --platform android --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-binaries
          path: |
            ./dist/
            target/**/bundle/**/*.{dmg,app,nsis,msi,ios}
            target/**/build/android/**/*.apk

  create-release:
    needs: build
    runs-on: macos-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            artifacts/**/*.{dmg,ios,nsis,msi,apk}
